### ISSUE TITLE
PDF export displays "Rendering plantuml diagram..."

### ISSUE THREAD

**Issue by jonas-klein** [marc0l92/joplin-plugin-plantUML#2]
When i export my Joplin notebook, containing PlantUML diagrams, to PDF, the exported PDF shows "Rendering plantuml diagram...". The Notebook displays the UML diagram correctly in its view. I used the following graph for testing the export, i don't tried other UML types.

    ```plantuml
    @startuml
    graph foo {
	    A, B, C, D, E [shape=circle]
	    rankdir=LR
      E -- {B D}
      A -- {D E}
      B -- D
      C -- {B E}
    }
    @enduml
    ```

## Environment

Joplin version: 2.4.12
Platform: Windows
OS specifics: Windows 10 Enterprise, Version 21H1, Build 19043.1237

## Steps to reproduce

1. Install the PlantUML-Plugin v1.4.1 (Tools>>Options>>Plugins>>Search for PlantUML>>Install>>Restart now)
2. Create a note and insert the abovementioned code
3. Export the Note to a PDF-file (File>>Export All>>PDF>>Save)

## What i've expected

The diagram should be exported to the PDF-file.

edit1: declared plugin version

**Comment by marc0l92** [comment]
That is a limitation of the current design.
It is not possible to read the settings from a markdown-it plugin, so I have to render the diagram using a javascript call to joplin to get the settings.

With this design you are able to set in the settings the format and rendering server.
On the other hand, the WYSIWYG and the pdf are not working.

I will try to cache the diagram URL in the markdown-it so that it works with the PDF export... even if I don't really know how to do it now.

... I will try to find a soution.

Thanks for your feedback

**Comment by marc0l92** [comment]
Please, try to update the plugin to v1.5.0 and let me know if you are now able to export in PDF with the diagrams pictures.

**Comment by jahoyne** [comment]
All good here with version 1.5.1. Diagrams show fine in exported PDF. 👍

Joplin 2.5.8 (prod, linux) appimage.

**Comment by jonas-klein** [comment]
yep, works like expected 👍  Thanks!
works in Joplin v2.4.12(prod, win32) and v2.5.8(prod, win23)

**Comment by marc0l92** [comment]
Thanks for your feedbacks

**Comment by zzFluke** [comment]
Unfortunately it doesn't work for me on 
MacOs BigSur 11.6 (20G165)
Joplin 2.5.10 (prod, darwin)
PlantUML2 v1.5.1

Exported PDF looks like this

![image](https://user-images.githubusercontent.com/2622004/140597221-0e4d0a26-5442-49ee-82a1-b1392ec62de5.png)

**Comment by marc0l92** [comment]
Thanks for letting me know,

unfortunatelly this fix uses some operating system dependent function and I was not able to test it on a mac.

I will try to find a mac to che why it is not working, otherwise I may need your help to debug this issue.

**Comment by marc0l92** [comment]
I tested on Mac the plugin and it works.

![Schermata 2021-11-07 alle 11 28 34](https://user-images.githubusercontent.com/12623073/140641404-00f3b2c9-d645-427c-84d6-c2657f1c6cd0.png)
![Schermata 2021-11-07 alle 11 27 15](https://user-images.githubusercontent.com/12623073/140641431-d444e207-2e0f-4658-bd71-14095e9b0472.png)
![Schermata 2021-11-07 alle 11 27 57](https://user-images.githubusercontent.com/12623073/140641457-dbf969d4-532b-4da9-9361-25256afd0741.png)

Since is not possible to execute the plugin Javascript while exporting the PDF, the plugin stores on disk a cache of the diagram that will be then used while creating the PDF.
The cache is deleted every time Joplin starts.
The cache is created when you open the note for the first time.
The cache is located in $TMPDIR/joplin-plantUml2-plugin

Try to follow those steps:
- Open Joplin
- Open the note that contains the PlantUML diagram
- Make sure the diagram is correctly cached in $TMPDIR/joplin-plantUml2-plugin
- Export in PDF the note

Let me know if you manage to find what is not working.
